spring.datasource.url=jdbc:mysql://localhost:3306/ecotrack_demo1?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# JWT
app.jwt.secret=5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
app.jwt.expiration-ms=86400000

# CORS: allow flutter app on emulator; adjust in production
server.port=8080
server.address=192.168.1.23


spring.servlet.encoding.charset=UTF-8
spring.servlet.encoding.enabled=true
spring.servlet.encoding.force=true
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

logging.level.org.springframework.security=DEBUG
logging.level.capstone_1.Ecotrack_backend=DEBUG

# Cau hinh EMAIL
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=dangvanhoang25121984@gmail.com
spring.mail.password=rzedpdojhsctsusd
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.debug=true

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Cloudinary Configuration
cloudinary.cloud-name=dufrrtxru
cloudinary.api-key=434428849861534
cloudinary.api-secret=hMglNM742ZvR19hNFjyfud2Y1jw
google.client-id=798523892228-hihng8k1s63khd4pcsp54fpgpqrdd60m.apps.googleusercontent.com